# Complete disease metadata with Hindi and English descriptions, remedies, and properties

DISEASE_DETAILS = {
    "Flu": {
        "name_en": "Influenza (Flu)",
        "name_hi": "फ्लू (इन्फ्लूएंजा)",
        "description_en": "Flu is a viral respiratory infection that causes fever, body aches, sore throat, cough, and severe fatigue.",
        "description_hi": "फ्लू एक संक्रामक वायरल श्वसन संक्रमण है जिसके मुख्य लक्षण तेज बुखार, बदन दर्द, गले में खराश, खांसी और अत्यधिक थकान हैं।",
        "severity": "mild",
        "severity_hi": "हल्का से मध्यम",
        "specialization": "General Medicine",
        "specialization_hi": "सामान्य चिकित्सा (General Physician)",
        "home_remedies_en": ["Get plenty of bed rest", "Drink warm fluids and herbal tea", "Steam inhalation for congestion", "Take light nutritious meals"],
        "home_remedies_hi": ["पर्याप्त आराम करें", "गुनगुना पानी और तुलसी-अदरक का काढ़ा पिएं", "गर्म पानी की भाप लें", "सुपाच्य और पौष्टिक भोजन लें"],
        "see_doctor_en": "Within 2 to 3 days if fever persists",
        "see_doctor_hi": "यदि 2-3 दिन तक बुखार बना रहे तो डॉक्टर से संपर्क करें",
        "emergency": False
    },
    "Common Cold": {
        "name_en": "Common Cold",
        "name_hi": "सामान्य जुकाम / सर्दी",
        "description_en": "The common cold is a viral infection of the nose and throat causing runny nose, sneezing, mild fever, and cough.",
        "description_hi": "सामान्य जुकाम नाक और गले का एक वायरल संक्रमण है, जिसमें बहती नाक, छींकें, हल्का बुखार और सूखी खांसी होती है।",
        "severity": "mild",
        "severity_hi": "हल्का",
        "specialization": "General Medicine",
        "specialization_hi": "सामान्य चिकित्सा (General Physician)",
        "home_remedies_en": ["Drink warm water", "Steam inhalation", "Salt water gargles for throat relief", "Rest adequately"],
        "home_remedies_hi": ["गर्म पानी पिएं", "दिन में 2 बार भाप लें", "गुनगुने नमक के पानी से गरारे करें", "आराम करें"],
        "see_doctor_en": "Not needed immediately unless symptoms worsen",
        "see_doctor_hi": "तुरंत जरूरत नहीं है, लक्षण बढ़ने पर डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Malaria": {
        "name_en": "Malaria",
        "name_hi": "मलेरिया",
        "description_en": "Malaria is a mosquito-borne infectious disease causing high fever with cyclical chills, intense sweating, headache, and body aches.",
        "description_hi": "मलेरिया मच्छर के काटने से होने वाला परजीवी संक्रमण है, जिसमें तेज ठंड लगकर कंपकंपी के साथ बुखार, पसीना और तेज सिरदर्द होता है।",
        "severity": "severe",
        "severity_hi": "गंभीर",
        "specialization": "General Medicine",
        "specialization_hi": "सामान्य चिकित्सा (General Physician)",
        "home_remedies_en": ["Consult doctor immediately for blood test", "Stay hydrated with ORS and electrolytes", "Cold compress on forehead for high fever", "Complete prescribed anti-malarial course"],
        "home_remedies_hi": ["तुरंत खून की जांच (MP test) करवाएं", "ओआरएस (ORS) और पर्याप्त तरल पदार्थ पिएं", "माथे पर ठंडे पानी की पट्टी रखें", "डॉक्टर द्वारा दी गई पूरी दवा का कोर्स करें"],
        "see_doctor_en": "Today urgently",
        "see_doctor_hi": "आज ही तुरंत डॉक्टर को दिखाएं",
        "emergency": True
    },
    "Dengue": {
        "name_en": "Dengue Fever",
        "name_hi": "डेंगू बुखार",
        "description_en": "Dengue is a viral infection spread by mosquitoes, characterized by high fever, severe joint and muscle pain, rash, and platelet drop.",
        "description_hi": "डेंगू एडीज मच्छर के काटने से फैलने वाला वायरल बुखार है, जिसमें तेज बुखार, जोड़ों व मांसपेशियों में असहनीय दर्द, त्वचा पर चकत्ते और प्लेटलेट्स कम होना शामिल है।",
        "severity": "severe",
        "severity_hi": "अत्यंत गंभीर",
        "specialization": "General Medicine",
        "specialization_hi": "सामान्य चिकित्सा (General Physician)",
        "home_remedies_en": ["Monitor platelet count regularly", "Drink papaya leaf extract, coconut water, and ORS", "Strict bed rest", "Avoid aspirin or ibuprofen"],
        "home_remedies_hi": ["नियमित रूप से प्लेटलेट्स काउंट चेक करवाएं", "पपीते के पत्तों का रस, नारियल पानी और ओआरएस पिएं", "पूरा आराम करें", "बिना डॉक्टर की सलाह कोई दर्द निवारक दवा न लें"],
        "see_doctor_en": "Today urgently",
        "see_doctor_hi": "आज ही तुरंत अस्पताल या डॉक्टर से संपर्क करें",
        "emergency": True
    },
    "Typhoid": {
        "name_en": "Typhoid Fever",
        "name_hi": "टाइफाइड (मियादी बुखार)",
        "description_en": "Typhoid is a bacterial infection caused by Salmonella typhi through contaminated food or water, leading to prolonged step-ladder fever and stomach pain.",
        "description_hi": "टाइफाइड दूषित पानी या भोजन से फैलने वाला जीवाणु संक्रमण है, जिसमें लगातार तेज बुखार, पेट दर्द, कमजोरी और भूख न लगना होता है।",
        "severity": "moderate",
        "severity_hi": "मध्यम से गंभीर",
        "specialization": "General Medicine",
        "specialization_hi": "सामान्य चिकित्सा (General Physician)",
        "home_remedies_en": ["Drink only boiled clean water", "Eat easily digestible foods (khichdi, porridge)", "Complete antibiotic regimen", "Maintain hand hygiene"],
        "home_remedies_hi": ["केवल उबला हुआ शुद्ध पानी पिएं", "हल्का व सुपाच्य भोजन (खिचड़ी, दलिया) खाएं", "एंटीबायोटिक का पूरा कोर्स करें", "हाथों की स्वच्छता का ध्यान रखें"],
        "see_doctor_en": "Within 2 days",
        "see_doctor_hi": "1-2 दिनों के भीतर डॉक्टर को दिखाएं",
        "emergency": False
    },
    "TB": {
        "name_en": "Tuberculosis (TB)",
        "name_hi": "टीबी (तपेदिक)",
        "description_en": "Tuberculosis is a bacterial infectious disease primarily affecting the lungs, causing long-lasting cough, chest pain, fever, and weight loss.",
        "description_hi": "टीबी फेफड़ों का एक गंभीर संक्रामक रोग है, जिसमें 2 सप्ताह से अधिक खांसी, सीने में दर्द, शाम के समय हल्का बुखार, पसीना और तेजी से वजन कम होता है।",
        "severity": "severe",
        "severity_hi": "गंभीर",
        "specialization": "Pulmonology",
        "specialization_hi": "फेफड़ा रोग विशेषज्ञ (Chest Specialist)",
        "home_remedies_en": ["Get free DOTS testing at nearest PHC/hospital", "Eat high protein diet", "Cover mouth while coughing", "Strict adherence to medication"],
        "home_remedies_hi": ["नजदीकी स्वास्थ्य केंद्र (PHC) पर बलगम की मुफ्त जांच करवाएं", "उच्च प्रोटीन युक्त आहार लें", "खांसते समय मुंह पर कपड़ा रखें", "दवाइयां नियमित रूप से लें"],
        "see_doctor_en": "Today urgently",
        "see_doctor_hi": "शीघ्र डॉक्टर से संपर्क करें",
        "emergency": False
    },
    "Pneumonia": {
        "name_en": "Pneumonia",
        "name_hi": "निमोनिया",
        "description_en": "Pneumonia is an infection that inflames the air sacs in one or both lungs, which may fill with fluid or pus causing painful breathing and fever.",
        "description_hi": "निमोनिया फेफड़ों का एक गंभीर संक्रमण है जिसमें फेफड़ों में सूजन और तरल जमा हो जाता है, जिससे सांस लेने में भारी तकलीफ, तेज बुखार और सीने में दर्द होता है।",
        "severity": "severe",
        "severity_hi": "गंभीर",
        "specialization": "Pulmonology",
        "specialization_hi": "फेफड़ा रोग विशेषज्ञ (Pulmonologist)",
        "home_remedies_en": ["Immediate clinical consultation and chest X-ray", "Stay in warm environment", "Drink warm fluids", "Do not delay medical treatment"],
        "home_remedies_hi": ["तुरंत डॉक्टर को दिखाकर छाती का एक्स-रे करवाएं", "गर्म वातावरण में रहें", "गुनगुना पानी व सूप पिएं", "इलाज में बिल्कुल देरी न करें"],
        "see_doctor_en": "Today urgently",
        "see_doctor_hi": "आज ही तुरंत डॉक्टर को दिखाएं",
        "emergency": True
    },
    "Diarrhea": {
        "name_en": "Diarrhea / Gastroenteritis",
        "name_hi": "दस्त / पेट का संक्रमण",
        "description_en": "Diarrhea is characterized by frequent loose, watery stools leading to rapid fluid and electrolyte loss.",
        "description_hi": "दस्त में बार-बार पतला पानी जैसा मल आता है, जिससे शरीर में पानी और आवश्यक लवणों की कमी (डिहाइड्रेशन) हो सकती है।",
        "severity": "moderate",
        "severity_hi": "मध्यम",
        "specialization": "General Medicine",
        "specialization_hi": "सामान्य चिकित्सा (General Physician)",
        "home_remedies_en": ["Drink ORS solution continuously", "Consume buttermilk, coconut water, and curd rice", "Avoid dairy, oily and spicy foods", "Maintain hydration"],
        "home_remedies_hi": ["ओआरएस (ORS) का घोल लगातार पिएं", "दही, छाछ, नारियल पानी और खिचड़ी खाएं", "तली-भुनी और मसालेदार चीजों से बचें", "पानी की कमी न होने दें"],
        "see_doctor_en": "Within 1 to 2 days",
        "see_doctor_hi": "यदि 24 घंटे में सुधार न हो तो डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Cholera": {
        "name_en": "Cholera",
        "name_hi": "हैजा (कॉलरा)",
        "description_en": "Cholera is an acute diarrheal illness caused by infection of the intestine with Vibrio cholerae bacteria, causing severe watery diarrhea and dehydration.",
        "description_hi": "हैजा दूषित पानी से होने वाला अत्यंत संक्रामक रोग है जिसमें चावल के पानी जैसे पतले दस्त और लगातार उल्टी से शरीर में पानी तुरंत खत्म हो जाता है।",
        "severity": "severe",
        "severity_hi": "अत्यंत गंभीर (आपातकालीन)",
        "specialization": "General Medicine",
        "specialization_hi": "सामान्य चिकित्सा / आपातकालीन सेवा",
        "home_remedies_en": ["Continuous heavy ORS hydration", "Seek emergency medical care for IV fluid support", "Boil all drinking water", "Isolate patient"],
        "home_remedies_hi": ["तुरंत ओआरएस घोल पिलाना शुरू करें", "बिना देरी किए अस्पताल जाकर ड्रिप (IV fluid) लगवाएं", "उबला हुआ पानी ही इस्तेमाल करें", "स्वच्छता बरतें"],
        "see_doctor_en": "Today urgently",
        "see_doctor_hi": "तुरंत अस्पताल / 108 एम्बुलेंस पर संपर्क करें",
        "emergency": True
    },
    "Food Poisoning": {
        "name_en": "Food Poisoning",
        "name_hi": "फूड पॉइजनिंग",
        "description_en": "Food poisoning is an illness caused by eating contaminated, spoiled, or toxic food, presenting with cramps, nausea, vomiting, and diarrhea.",
        "description_hi": "बासी, दूषित या विषैला भोजन करने से पेट में तेज मरोड़, उल्टी, दस्त, कमजोरी और हल्का बुखार हो जाता है।",
        "severity": "moderate",
        "severity_hi": "मध्यम",
        "specialization": "General Medicine",
        "specialization_hi": "सामान्य चिकित्सा (General Physician)",
        "home_remedies_en": ["Sip ORS and clear fluids slowly", "Rest the stomach with light food (bananas, rice)", "Avoid solid heavy food for 12 hours", "Do not suppress vomiting initially"],
        "home_remedies_hi": ["ओआरएस और नींबू पानी घूंट-घूंट कर पिएं", "केला, उबले चावल और मूंग दाल का पानी लें", "भारी और तला भोजन न करें", "पर्याप्त आराम करें"],
        "see_doctor_en": "Within 2 days",
        "see_doctor_hi": "यदि उल्टी-दस्त न रुके तो डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Jaundice": {
        "name_en": "Jaundice",
        "name_hi": "पीलिया (जॉन्डिस)",
        "description_en": "Jaundice causes yellowish pigmentation of the skin and whites of the eyes due to high levels of bilirubin in the blood.",
        "description_hi": "पीलिया में रक्त में बिलीरुबिन बढ़ने के कारण आंखें, त्वचा और पेशाब का रंग पीला हो जाता है, साथ में भूख न लगना और कमजोरी महसूस होती है।",
        "severity": "moderate",
        "severity_hi": "मध्यम से गंभीर",
        "specialization": "Gastroenterology",
        "specialization_hi": "पेट व लिवर विशेषज्ञ (Gastroenterologist)",
        "home_remedies_en": ["Get liver function test (LFT) done", "Drink sugarcane juice and plenty of clean water", "Eat boiled bland food without oil/spices", "Complete physical rest"],
        "home_remedies_hi": ["लिवर फंक्शन टेस्ट (LFT) करवाएं", "गन्ने का ताजा रस और खूब साफ पानी पिएं", "बिना तेल-मसाले का उबला सादा खाना खाएं", "पूर्ण आराम करें"],
        "see_doctor_en": "Within 2 days",
        "see_doctor_hi": "2 दिनों के भीतर डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Hepatitis": {
        "name_en": "Hepatitis",
        "name_hi": "हेपेटाइटिस (लिवर सूजन)",
        "description_en": "Hepatitis is an inflammation of the liver caused by viral infection, presenting with fatigue, dark urine, and abdominal pain.",
        "description_hi": "हेपेटाइटिस लिवर में वायरल संक्रमण से होने वाली सूजन है, जिससे पेट दर्द, अत्यधिक कमजोरी, गहरा पेशाब और भूख की कमी होती है।",
        "severity": "severe",
        "severity_hi": "गंभीर",
        "specialization": "Gastroenterology",
        "specialization_hi": "पेट व लिवर विशेषज्ञ (Gastroenterologist)",
        "home_remedies_en": ["Consult doctor for viral screening", "Avoid alcohol and fatty foods completely", "Take high carbohydrate easy-to-digest diet", "Adequate rest"],
        "home_remedies_hi": ["डॉक्टर से जांच करवाकर उचित दवा लें", "शराब और चिकनाई वाले खाने से पूर्ण परहेज करें", "हल्का व सुपाच्य भोजन लें", "पर्याप्त आराम करें"],
        "see_doctor_en": "Today urgently",
        "see_doctor_hi": "शीघ्र डॉक्टर से परामर्श लें",
        "emergency": False
    },
    "Diabetes": {
        "name_en": "Diabetes Mellitus",
        "name_hi": "मधुमेह (डायबिटीज / शुगर)",
        "description_en": "Diabetes is a chronic metabolic condition where blood glucose levels are consistently high, causing frequent urination, extreme thirst, and fatigue.",
        "description_hi": "मधुमेह में रक्त में शर्करा (शुगर) का स्तर बढ़ जाता है, जिससे बार-बार पेशाब आना, अत्यधिक प्यास लगना, थकान और घाव देर से भरना जैसे लक्षण होते हैं।",
        "severity": "moderate",
        "severity_hi": "मध्यम (दीर्घकालिक)",
        "specialization": "Endocrinology",
        "specialization_hi": "मधुमेह विशेषज्ञ (Endocrinologist / Physician)",
        "home_remedies_en": ["Check fasting and post-meal blood sugar", "Engage in 30 minutes daily walking", "Eliminate refined sugar and sweets", "Eat high-fiber vegetables and whole grains"],
        "home_remedies_hi": ["खाली पेट व खाने के बाद शुगर की जांच करवाएं", "रोज 30 मिनट टहलें", "चीनी, मिठाई और मीठे पेय पदार्थों से बचें", "करेला, मेथी और फाइबर युक्त आहार लें"],
        "see_doctor_en": "Within a week",
        "see_doctor_hi": "एक सप्ताह के भीतर डॉक्टर से मिलकर दवा तय करें",
        "emergency": False
    },
    "Hypertension": {
        "name_en": "Hypertension (High BP)",
        "name_hi": "उच्च रक्तचाप (हाई ब्लड प्रेशर)",
        "description_en": "Hypertension is persistently elevated arterial pressure, often asymptomatic or causing morning headache, dizziness, and palpitations.",
        "description_hi": "हाई ब्लड प्रेशर में धमनियों में रक्त का दबाव बढ़ जाता है, जिससे सिर में भारीपन, चक्कर आना, घबराहट और सांस फूलने की समस्या हो सकती है।",
        "severity": "moderate",
        "severity_hi": "मध्यम",
        "specialization": "Cardiology",
        "specialization_hi": "हृदय रोग / फिजिशियन (Cardiologist)",
        "home_remedies_en": ["Measure blood pressure immediately", "Reduce dietary salt intake significantly", "Practice deep breathing and avoid stress", "Take prescribed antihypertensives regularly"],
        "home_remedies_hi": ["तुरंत अपना ब्लड प्रेशर नापें", "खाने में नमक की मात्रा कम करें", "तनाव से बचें और प्राणायाम करें", "डॉक्टर की दी हुई बीपी की दवा समय पर लें"],
        "see_doctor_en": "Within 2 days",
        "see_doctor_hi": "2 दिनों के भीतर डॉक्टर से संपर्क करें",
        "emergency": False
    },
    "Heart Disease": {
        "name_en": "Heart Disease / Cardiac Issue",
        "name_hi": "हृदय रोग (दिल की बीमारी)",
        "description_en": "Heart conditions can cause chest discomfort, pain radiating to arm/jaw, shortness of breath, palpitations, and cold sweats.",
        "description_hi": "हृदय रोग में सीने में दबाव या तेज दर्द, बाएं हाथ या जबड़े में दर्द का फैलना, सांस फूलना, पसीना और घबराहट होती है।",
        "severity": "severe",
        "severity_hi": "अत्यंत गंभीर (आपातकालीन)",
        "specialization": "Cardiology",
        "specialization_hi": "हृदय रोग विशेषज्ञ (Cardiologist)",
        "home_remedies_en": ["Stop all physical activity and sit upright", "Take prescribed emergency medication if advised by doctor", "Do not ignore chest pressure", "Call ambulance immediately"],
        "home_remedies_hi": ["तुरंत बैठ जाएं और कोई भारी काम न करें", "यदि पहले से डॉक्टर की आपातकालीन गोली हो तो लें", "सीने के दर्द को बिल्कुल नजरअंदाज न करें", "तुरंत 108 पर कॉल करें"],
        "see_doctor_en": "Today urgently",
        "see_doctor_hi": "तुरंत आपातकालीन अस्पताल पहुंचें (108 पर कॉल करें)",
        "emergency": True
    },
    "Asthma": {
        "name_en": "Bronchial Asthma",
        "name_hi": "अस्थमा (दमा)",
        "description_en": "Asthma is a chronic condition causing inflammation and narrowing of airways, leading to wheezing, chest tightness, and shortness of breath.",
        "description_hi": "अस्थमा में श्वास नलिकाओं में सूजन और सिकुड़न हो जाती है, जिससे सांस लेते समय सीटी की आवाज (wheezing), छाती में जकड़न और सांस फूलती है।",
        "severity": "moderate",
        "severity_hi": "मध्यम से गंभीर",
        "specialization": "Pulmonology",
        "specialization_hi": "फेफड़ा रोग विशेषज्ञ (Chest Specialist)",
        "home_remedies_en": ["Use prescribed rescue inhaler immediately", "Sit upright in a well-ventilated dust-free room", "Avoid cold air, smoke, and allergens", "Take steam inhalation"],
        "home_remedies_hi": ["डॉक्टर द्वारा दिया गया इनहेलर (Inhaler) तुरंत लें", "सीधे बैठें और धूल-धुएं से दूर रहें", "ठंडी हवा और एलर्जी वाली चीजों से बचें", "भाप लें"],
        "see_doctor_en": "Today urgently if inhaler does not relieve",
        "see_doctor_hi": "यदि इनहेलर से आराम न मिले तो आज ही डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Bronchitis": {
        "name_en": "Bronchitis",
        "name_hi": "ब्रोंकाइटिस (श्वसन नली में सूजन)",
        "description_en": "Bronchitis is inflammation of the bronchial tubes causing mucus-producing cough, fatigue, chest soreness, and mild fever.",
        "description_hi": "ब्रोंकाइटिस में फेफड़ों की वायु नलियों में सूजन आ जाती है, जिससे बलगम वाली लगातार खांसी, छाती में दर्द और हल्का बुखार होता है।",
        "severity": "moderate",
        "severity_hi": "मध्यम",
        "specialization": "Pulmonology",
        "specialization_hi": "फेफड़ा रोग विशेषज्ञ (Pulmonologist)",
        "home_remedies_en": ["Take warm steam with eucalyptus oil", "Drink warm honey water and ginger tea", "Avoid smoking and dust exposure", "Rest your chest"],
        "home_remedies_hi": ["गर्म पानी की भाप लें", "शहद-अदरक का रस और गुनगुना पानी पिएं", "धूम्रपान और धूल से बचें", "पर्याप्त आराम करें"],
        "see_doctor_en": "Within 2 to 3 days",
        "see_doctor_hi": "2-3 दिनों में डॉक्टर से परामर्श करें",
        "emergency": False
    },
    "Anemia": {
        "name_en": "Anemia (Iron Deficiency)",
        "name_hi": "एनीमिया (खून की कमी)",
        "description_en": "Anemia occurs when the blood lacks sufficient healthy red blood cells or hemoglobin, causing extreme tiredness, paleness, and dizziness.",
        "description_hi": "एनीमिया में शरीर में हीमोग्लोबिन या लाल रक्त कोशिकाओं की कमी हो जाती है, जिससे चेहरे पर पीलापन, चक्कर आना, जल्दी थक जाना और कमजोरी होती है।",
        "severity": "moderate",
        "severity_hi": "मध्यम",
        "specialization": "General Medicine",
        "specialization_hi": "सामान्य चिकित्सा (General Physician)",
        "home_remedies_en": ["Eat iron-rich foods (spinach, jaggery, beetroot, pomegranate)", "Take doctor-prescribed iron & folic acid tablets", "Include Vitamin C foods (lemon, amla) for absorption", "Avoid tea/coffee immediately after meals"],
        "home_remedies_hi": ["आयरन युक्त आहार (पालक, गुड़, चुकंदर, अनार) खाएं", "आयरन और फोलिक एसिड की गोलियां लें", "विटामिन सी (नींबू, आंवला) लें ताकि आयरन सोख सके", "खाने के तुरंत बाद चाय-कॉफी न पिएं"],
        "see_doctor_en": "Within a week",
        "see_doctor_hi": "एक सप्ताह के भीतर खून की जांच करवाकर डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Malnutrition": {
        "name_en": "Malnutrition",
        "name_hi": "कुपोषण",
        "description_en": "Malnutrition results from insufficient or unbalanced nutrient intake, leading to weakness, weight loss, stunted growth, and lowered immunity.",
        "description_hi": "संतुलित और पोषक तत्वों से भरपूर भोजन न मिलने के कारण शरीर कमजोर हो जाता है, वजन घटता है और रोग प्रतिरोधक क्षमता कम हो जाती है।",
        "severity": "moderate",
        "severity_hi": "मध्यम",
        "specialization": "Pediatrics / General",
        "specialization_hi": "बाल रोग विशेषज्ञ / पोषण विशेषज्ञ",
        "home_remedies_en": ["Provide calorie and protein-dense foods (eggs, pulses, milk, bananas)", "Ensure regular feeding routine", "Include green vegetables and fruits", "Visit nearest Anganwadi for nutritional supplements"],
        "home_remedies_hi": ["प्रोटीन और कैलोरी युक्त भोजन (दालें, दूध, अंडा, केला) दें", "नियमित अंतराल पर पौष्टिक आहार खिलाएं", "हरी सब्जियां और फल शामिल करें", "आंगनवाड़ी से पोषण सप्लीमेंट प्राप्त करें"],
        "see_doctor_en": "Within a week",
        "see_doctor_hi": "एक सप्ताह के भीतर स्वास्थ्य केंद्र या डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Scabies": {
        "name_en": "Scabies",
        "name_hi": "स्केबीज (खुजली का संक्रामक रोग)",
        "description_en": "Scabies is an intensely itchy skin condition caused by microscopic burrowing mites, particularly severe at night.",
        "description_hi": "स्केबीज सूक्ष्म कीटाणुओं (माइट्स) के कारण होने वाला अत्यधिक संक्रामक त्वचा रोग है, जिसमें विशेषकर रात में तेज खुजली और बारीक दाने होते हैं।",
        "severity": "mild",
        "severity_hi": "हल्का से मध्यम",
        "specialization": "Dermatology",
        "specialization_hi": "त्वचा रोग विशेषज्ञ (Dermatologist)",
        "home_remedies_en": ["Apply prescribed permethrin lotion all over the body", "Wash all clothes and bedding in hot boiling water", "Treat all household members simultaneously", "Avoid sharing towels/bedsheets"],
        "home_remedies_hi": ["डॉक्टर की बताई परमेथ्रिन लोशन पूरे शरीर पर लगाएं", "कपड़े और बिस्तर गर्म पानी में धोकर धूप में सुखाएं", "परिवार के सभी सदस्यों का एक साथ इलाज करें", "तौलिया व कपड़े अलग रखें"],
        "see_doctor_en": "Within 2 to 3 days",
        "see_doctor_hi": "2-3 दिनों में डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Ringworm": {
        "name_en": "Ringworm (Fungal Infection)",
        "name_hi": "दाद (फंगल इन्फेक्शन)",
        "description_en": "Ringworm is a common fungal skin infection producing circular, red, itchy raised rashes with clearer centers.",
        "description_hi": "दाद फफूंद (फंगस) से होने वाला गोल चकत्तेदार त्वचा संक्रमण है, जिसमें किनारों पर लाल दाने और तेज खुजली होती है।",
        "severity": "mild",
        "severity_hi": "हल्का",
        "specialization": "Dermatology",
        "specialization_hi": "त्वचा रोग विशेषज्ञ (Dermatologist)",
        "home_remedies_en": ["Apply antifungal cream (clotrimazole) regularly", "Keep infected skin dry and clean", "Wear loose cotton clothes", "Do not scratch the patches"],
        "home_remedies_hi": ["एंटीफंगल क्रीम (क्लॉट्रीमाज़ोल) दिन में 2 बार लगाएं", "प्रभावित जगह को सूखा और साफ रखें", "ढीले सूती कपड़े पहनें", "दाद को खुजलाने से बचें"],
        "see_doctor_en": "Within a week",
        "see_doctor_hi": "यदि 1 सप्ताह में आराम न हो तो डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Chickenpox": {
        "name_en": "Chickenpox",
        "name_hi": "चिकनपॉक्स (चेचक / छोटी माता)",
        "description_en": "Chickenpox is a highly contagious viral infection characterized by an itchy blister-like rash, mild fever, and fatigue.",
        "description_hi": "चिकनपॉक्स एक वायरल संक्रमण है जिसमें पूरे शरीर पर पानी भरे खुजलीदार दाने, हल्का बुखार, बदन दर्द और भूख में कमी होती है।",
        "severity": "moderate",
        "severity_hi": "मध्यम",
        "specialization": "Pediatrics / General",
        "specialization_hi": "बाल रोग विशेषज्ञ / सामान्य चिकित्सक",
        "home_remedies_en": ["Apply calamine lotion for itch relief", "Take sponge baths with neem water", "Trim nails to prevent scratching and secondary infection", "Isolate patient until blisters dry"],
        "home_remedies_hi": ["खुजली कम करने के लिए कैलामाइन लोशन लगाएं", "नीम के पानी से शरीर साफ करें", "नाखून छोटे रखें ताकि खरोंच न लगे", "दाने सूखने तक मरीज को अलग कमरे में रखें"],
        "see_doctor_en": "Within 2 days",
        "see_doctor_hi": "2 दिनों के भीतर डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Measles": {
        "name_en": "Measles",
        "name_hi": "खसरा (मीजल्स)",
        "description_en": "Measles is a serious viral infection causing high fever, cough, runny nose, red eyes, and a widespread red blotchy rash.",
        "description_hi": "खसरा एक संक्रामक वायरल बीमारी है जिसमें तेज बुखार, खांसी, बहती नाक, लाल आंखें और चेहरे से शुरू होकर पूरे शरीर पर लाल दाने फैलते हैं।",
        "severity": "severe",
        "severity_hi": "गंभीर",
        "specialization": "Pediatrics",
        "specialization_hi": "बाल रोग विशेषज्ञ (Pediatrician)",
        "home_remedies_en": ["Consult doctor for Vitamin A supplementation", "Keep patient in dim, comfortable room to protect eyes", "Maintain high fluid intake", "Ensure MMR vaccination for contacts"],
        "home_remedies_hi": ["डॉक्टर की सलाह से विटामिन ए की खुराक लें", "आंखों को तेज रोशनी से बचाएं और कमरे में मंद प्रकाश रखें", "खूब पानी और तरल आहार दें", "अन्य बच्चों का टीकाकरण सुनिश्चित करें"],
        "see_doctor_en": "Today urgently",
        "see_doctor_hi": "आज ही तुरंत डॉक्टर को दिखाएं",
        "emergency": True
    },
    "Mumps": {
        "name_en": "Mumps",
        "name_hi": "कण्ठमाला (गलसुआ / मम्प्स)",
        "description_en": "Mumps is a viral infection that primarily affects the saliva-producing parotid glands located near the ears, causing painful swelling.",
        "description_hi": "मम्प्स में कान के नीचे स्थित लार ग्रंथियों में सूजन आ जाती है, जिससे गाल सूज जाते हैं और चबाने या निगलने में तेज दर्द होता है।",
        "severity": "moderate",
        "severity_hi": "मध्यम",
        "specialization": "Pediatrics / General",
        "specialization_hi": "सामान्य चिकित्सक / बाल रोग विशेषज्ञ",
        "home_remedies_en": ["Apply warm or cold compress to swollen cheeks", "Eat soft foods that do not require chewing (soups, porridge)", "Avoid sour foods that trigger saliva", "Drink plenty of water"],
        "home_remedies_hi": ["गालों की सूजन पर गर्म या ठंडी सिकाई करें", "नरम खाना खाएं जिसे चबाना न पड़े (खिचड़ी, सूप)", "खट्टी चीजों से बचें जिनसे लार बनती है", "खूब पानी पिएं"],
        "see_doctor_en": "Within 2 days",
        "see_doctor_hi": "2 दिनों के भीतर डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Conjunctivitis": {
        "name_en": "Conjunctivitis (Pink Eye)",
        "name_hi": "आंख आना (कंजंक्टिवाइटिस)",
        "description_en": "Conjunctivitis is an inflammation of the clear membrane lining the eyelid and white part of eyeball, causing redness, discharge, and grittiness.",
        "description_hi": "आंख आने में आंखें लाल हो जाती हैं, पानी और चिपचिपा कीचड़ निकलता है, तथा आंखों में चुभन और जलन महसूस होती है।",
        "severity": "mild",
        "severity_hi": "हल्का",
        "specialization": "Ophthalmology",
        "specialization_hi": "नेत्र रोग विशेषज्ञ (Eye Specialist)",
        "home_remedies_en": ["Wash eyes gently with clean boiled cool water", "Use doctor-prescribed antibiotic eye drops", "Do not touch or rub eyes with hands", "Use separate towels to prevent family spread"],
        "home_remedies_hi": ["उबले और ठंडे साफ पानी से आंखें धोएं", "डॉक्टर द्वारा बताई आई ड्रॉप्स डालें", "हाथों से आंखों को बिल्कुल न मलें", "अपना तौलिया और तकिया अलग रखें"],
        "see_doctor_en": "Within 2 days",
        "see_doctor_hi": "2 दिनों के भीतर नेत्र चिकित्सक को दिखाएं",
        "emergency": False
    },
    "Sinusitis": {
        "name_en": "Sinusitis",
        "name_hi": "साइनस (साइनोसाइटिस)",
        "description_en": "Sinusitis is inflammation of the air cavities in the passages of the nose, leading to facial pressure, headache, and nasal congestion.",
        "description_hi": "साइनस में नाक के आसपास की वायु गुहाओं में सूजन और बलगम भर जाता है, जिससे माथे व गालों में भारीपन, तेज सिरदर्द और बंद नाक होती है।",
        "severity": "mild",
        "severity_hi": "हल्का से मध्यम",
        "specialization": "ENT",
        "specialization_hi": "कान, नाक, गला विशेषज्ञ (ENT Specialist)",
        "home_remedies_en": ["Inhale warm steam 2-3 times daily", "Use saline nasal spray for congestion", "Drink warm fluids", "Apply warm towel on face"],
        "home_remedies_hi": ["दिन में 2-3 बार गर्म पानी की भाप लें", "सलाइन नेजल ड्रॉप्स का प्रयोग करें", "गर्म पानी और सूप पिएं", "चेहरे पर गर्म तौलिए से सिकाई करें"],
        "see_doctor_en": "Within 3 to 4 days",
        "see_doctor_hi": "3-4 दिनों में आराम न होने पर डॉक्टर को दिखाएं",
        "emergency": False
    },
    "UTI": {
        "name_en": "Urinary Tract Infection (UTI)",
        "name_hi": "पेशाब का संक्रमण (UTI)",
        "description_en": "A UTI is a bacterial infection of the urinary system causing burning sensation during urination, frequent urge, cloudy urine, and pelvic pain.",
        "description_hi": "यूटीआई में पेशाब करते समय तेज जलन, बार-बार पेशाब की इच्छा, पेशाब का रंग गहरा होना और पेडू में दर्द की शिकायत होती है।",
        "severity": "moderate",
        "severity_hi": "मध्यम",
        "specialization": "Nephrology / General",
        "specialization_hi": "गुर्दा व मूत्र रोग विशेषज्ञ / फिजिशियन",
        "home_remedies_en": ["Drink 3-4 liters of water daily to flush bacteria", "Take prescribed course of antibiotics", "Drink unsweetened cranberry or barley water", "Maintain private hygiene"],
        "home_remedies_hi": ["रोजाना 3-4 लीटर पानी पिएं ताकि बैक्टीरिया बाहर निकले", "डॉक्टर की दी हुई एंटीबायोटिक का पूरा कोर्स करें", "जौ का पानी या नारियल पानी पिएं", "शौच व स्वच्छता का विशेष ध्यान रखें"],
        "see_doctor_en": "Within 2 days",
        "see_doctor_hi": "1-2 दिनों के भीतर डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Kidney Stone": {
        "name_en": "Kidney Stone",
        "name_hi": "गुर्दे की पथरी (किडनी स्टोन)",
        "description_en": "Kidney stones are hard mineral deposits in the kidneys causing excruciating spasmodic pain in the lower back radiating to the groin, with blood in urine.",
        "description_hi": "गुर्दे में पथरी बनने से कमर के एक तरफ असहनीय तेज दर्द उठता है जो नीचे पेट की ओर जाता है, साथ में पेशाब में जलन व खून आ सकता है।",
        "severity": "severe",
        "severity_hi": "गंभीर",
        "specialization": "Nephrology / Urology",
        "specialization_hi": "मूत्र व गुर्दा रोग विशेषज्ञ (Urologist)",
        "home_remedies_en": ["Drink plenty of water (4+ liters/day)", "Get ultrasound (USG) of abdomen done", "Take pain relief under medical guidance", "Avoid high oxalate foods (spinach, tomato seeds)"],
        "home_remedies_hi": ["खूब सारा पानी पिएं (दिन में 3-4 लीटर)", "पेट का अल्ट्रासाउंड (USG) करवाएं", "डॉक्टर की सलाह से दर्द निवारक लें", "पालक, टमाटर के बीज व ज्यादा नमक से परहेज करें"],
        "see_doctor_en": "Today urgently for severe colic pain",
        "see_doctor_hi": "तेज दर्द होने पर आज ही तुरंत डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Arthritis": {
        "name_en": "Arthritis (Joint Inflammation)",
        "name_hi": "गठिया (जोड़ों का दर्द व सूजन)",
        "description_en": "Arthritis causes inflammation and stiffness of one or more joints, leading to swelling, restricted mobility, and chronic pain.",
        "description_hi": "गठिया में जोड़ों में सूजन, जकड़न और तेज दर्द होता है, जिससे उठने-बैठने और चलने-फिरने में काफी परेशानी होती है।",
        "severity": "moderate",
        "severity_hi": "मध्यम",
        "specialization": "Orthopedics / Rheumatology",
        "specialization_hi": "हड्डी व जोड़ रोग विशेषज्ञ (Orthopedic)",
        "home_remedies_en": ["Apply warm compress or hot water bag on joints", "Perform gentle stretching and low-impact exercises", "Consume turmeric milk (curcumin) for inflammation", "Maintain healthy body weight"],
        "home_remedies_hi": ["जोड़ों पर गर्म पानी की थैली से सिकाई करें", "हल्का व्यायाम व टहलना जारी रखें", "हल्दी वाला दूध पिएं", "शरीर का वजन नियंत्रित रखें"],
        "see_doctor_en": "Within a week",
        "see_doctor_hi": "एक सप्ताह में हड्डी के डॉक्टर से परामर्श लें",
        "emergency": False
    },
    "Back Pain": {
        "name_en": "Back Pain / Lumbago",
        "name_hi": "कमर दर्द (पीठ दर्द)",
        "description_en": "Back pain is caused by muscle strain, poor posture, or spinal disc irritation, creating dull or sharp pain in the lumbar region.",
        "description_hi": "गलत तरीके से बैठने, भारी वजन उठाने या मांसपेशियों में खिंचाव से पीठ व कमर के निचले हिस्से में तेज दर्द और अकड़न हो जाती है।",
        "severity": "mild",
        "severity_hi": "हल्का से मध्यम",
        "specialization": "Orthopedics / Physiotherapy",
        "specialization_hi": "हड्डी रोग विशेषज्ञ / फिजियोथेरेपिस्ट",
        "home_remedies_en": ["Apply hot and cold pack alternately", "Avoid lifting heavy loads and maintain straight posture", "Sleep on a firm supportive mattress", "Do gentle back strengthening exercises"],
        "home_remedies_hi": ["गर्म पानी की बोतल या सिकाई करें", "भारी वजन न उठाएं और रीढ़ सीधी रखकर बैठें", "सख्त गद्दे पर सोएं", "हल्के कमर के योगासन करें"],
        "see_doctor_en": "Within a week if pain radiates to legs",
        "see_doctor_hi": "यदि दर्द पैरों तक जाए तो डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Migraine": {
        "name_en": "Migraine Headache",
        "name_hi": "माइग्रेन (आधासीसी सिरदर्द)",
        "description_en": "Migraine is a neurological condition causing intense throbbing headache typically on one side of the head, accompanied by nausea and light sensitivity.",
        "description_hi": "माइग्रेन में सिर के एक हिस्से में तेज धड़कन जैसा दर्द होता है, साथ में जी मिचलाना, उल्टी और रोशनी व आवाज से घबराहट होती है।",
        "severity": "moderate",
        "severity_hi": "मध्यम से गंभीर",
        "specialization": "Neurology",
        "specialization_hi": "स्नायु रोग विशेषज्ञ (Neurologist)",
        "home_remedies_en": ["Rest in a dark, quiet and cool room", "Apply cold compress on the forehead", "Stay hydrated and avoid skipping meals", "Avoid known triggers (loud noise, stress)"],
        "home_remedies_hi": ["अंधेरे और शांत कमरे में आराम करें", "माथे पर ठंडी पट्टी रखें", "पर्याप्त पानी पिएं और समय पर खाना खाएं", "तेज धूप, शोर और तनाव से बचें"],
        "see_doctor_en": "Within 2 to 3 days",
        "see_doctor_hi": "2-3 दिनों में डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Epilepsy": {
        "name_en": "Epilepsy / Seizure Disorder",
        "name_hi": "मिर्गी (दौरे पड़ना)",
        "description_en": "Epilepsy is a central nervous system disorder in which brain activity becomes abnormal, causing recurrent seizures or periods of unusual behavior.",
        "description_hi": "मिर्गी मस्तिष्क का विकार है जिसमें दिमाग की तंत्रिकाओं में अचानक करंट जैसे झटके आने से बेहोशी, शरीर का अकड़ना और दौरे पड़ते हैं।",
        "severity": "severe",
        "severity_hi": "गंभीर",
        "specialization": "Neurology",
        "specialization_hi": "न्यूरोलॉजिस्ट (Neurologist)",
        "home_remedies_en": ["During seizure, turn patient on one side and clear surroundings", "Never put anything in patient's mouth during fit", "Take prescribed antiepileptic medicines without fail", "Ensure 8 hours of sound sleep"],
        "home_remedies_hi": ["दौरे के समय मरीज को करवट लिटाएं और आसपास की चीजें हटाएं", "मुंह में जूता-चम्मच न ठूंसें", "डॉक्टर की मिर्गी की दवा कभी न छोड़ें", "पर्याप्त 8 घंटे की नींद लें"],
        "see_doctor_en": "Today urgently",
        "see_doctor_hi": "तुरंत न्यूरोलॉजिस्ट से मिलें",
        "emergency": True
    },
    "Depression": {
        "name_en": "Depression",
        "name_hi": "डिप्रेशन (अवसाद)",
        "description_en": "Depression is a mood disorder causing persistent feelings of sadness, loss of interest, fatigue, sleep disturbances, and hopelessness.",
        "description_hi": "डिप्रेशन में लंबे समय तक मन उदास रहना, किसी काम में मन न लगना, अत्यधिक थकान, नींद न आना और जीवन के प्रति नकारात्मक विचार आते हैं।",
        "severity": "moderate",
        "severity_hi": "मध्यम",
        "specialization": "Psychiatry",
        "specialization_hi": "मनोरोग विशेषज्ञ (Psychiatrist / Counselor)",
        "home_remedies_en": ["Talk openly with trusted friends and family", "Practice regular physical exercise and meditation", "Maintain a consistent sleep and meal schedule", "Seek professional mental health counseling"],
        "home_remedies_hi": ["अपने परिजनों और दोस्तों से खुलकर बात करें", "प्रतिदिन टहलें और योग/ध्यान करें", "समय पर सोने और जागने की आदत डालें", "मनोचिकित्सक से परामर्श लें"],
        "see_doctor_en": "Within a week",
        "see_doctor_hi": "एक सप्ताह के भीतर मनोचिकित्सक से मिलें",
        "emergency": False
    },
    "Anxiety": {
        "name_en": "Anxiety Disorder",
        "name_hi": "घबराहट / चिंता विकार",
        "description_en": "Anxiety causes feelings of intense worry, fear, rapid heart rate, sweating, dizziness, and restlessness in daily situations.",
        "description_hi": "चिंता विकार में बिना किसी बड़े कारण के अचानक तेज घबराहट, दिल की धड़कन तेज होना, पसीना छूटना और बेचैनी महसूस होती है।",
        "severity": "moderate",
        "severity_hi": "मध्यम",
        "specialization": "Psychiatry",
        "specialization_hi": "मनोरोग विशेषज्ञ (Psychiatrist)",
        "home_remedies_en": ["Practice slow deep breathing (4-7-8 method)", "Limit caffeine and tea intake", "Take brisk morning walks in nature", "Practice mindfulness"],
        "home_remedies_hi": ["गहरी लंबी सांसें लें (अनुलोम-विलोम करें)", "चाय-कॉफी कम पिएं", "सुबह खुली हवा में टहलें", "तनाव कम करने का प्रयास करें"],
        "see_doctor_en": "Within a week",
        "see_doctor_hi": "एक सप्ताह में डॉक्टर से सलाह लें",
        "emergency": False
    },
    "Appendicitis": {
        "name_en": "Appendicitis",
        "name_hi": "अपेंडिसाइटिस (अपेंडिक्स सूजन)",
        "description_en": "Appendicitis is acute inflammation of the appendix causing sudden severe pain in the lower right abdomen, fever, nausea, and vomiting.",
        "description_hi": "अपेंडिक्स में अचानक संक्रमण व सूजन से पेट के निचले दाएं हिस्से में असहनीय तेज दर्द, उल्टी और बुखार हो जाता है।",
        "severity": "severe",
        "severity_hi": "अत्यंत गंभीर (सर्जरी की जरूरत)",
        "specialization": "General Surgery",
        "specialization_hi": "सर्जन / आपातकालीन चिकित्सा (Surgeon)",
        "home_remedies_en": ["Do not eat or drink anything until doctor examines", "Do not apply heat pads or take strong pain killers", "Rush to nearest emergency hospital immediately", "Requires surgical evaluation"],
        "home_remedies_hi": ["मरीज को कुछ भी खाने-पीने को न दें", "पेट पर गर्म सिकाई न करें", "तुरंत नजदीकी अस्पताल के इमरजेंसी में जाएं", "इलाज में बिल्कुल देरी न करें"],
        "see_doctor_en": "Today urgently",
        "see_doctor_hi": "आज ही तुरंत अस्पताल पहुंचें",
        "emergency": True
    },
    "Gastritis": {
        "name_en": "Gastritis / Acidity",
        "name_hi": "गैस्ट्राइटिस (पेट में गैस व जलन)",
        "description_en": "Gastritis is inflammation of the stomach lining causing burning upper abdominal pain, nausea, bloating, and indigestion.",
        "description_hi": "पेट की अंदरूनी परत में सूजन से पेट के ऊपरी हिस्से में जलन, खट्टी डकारें, गैस, मतली और भारीपन की समस्या होती है।",
        "severity": "mild",
        "severity_hi": "हल्का",
        "specialization": "Gastroenterology",
        "specialization_hi": "पेट रोग विशेषज्ञ / फिजिशियन",
        "home_remedies_en": ["Drink cold milk or coconut water", "Eat small frequent light meals", "Avoid spicy, fried and junk foods", "Do not stay on empty stomach for long hours"],
        "home_remedies_hi": ["ठंडा दूध या नारियल पानी पिएं", "थोड़ी-थोड़ी देर में हल्का खाना खाएं", "ज्यादा मिर्च-मसाले और तली चीजों से बचें", "ज्यादा देर भूखे न रहें"],
        "see_doctor_en": "Within 3 to 4 days if persistent",
        "see_doctor_hi": "3-4 दिनों में आराम न मिले तो डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Constipation": {
        "name_en": "Constipation",
        "name_hi": "कब्ज (कॉन्स्टिपेशन)",
        "description_en": "Constipation is a condition where bowel movements are infrequent or stools are hard and difficult to pass, causing bloating and abdominal discomfort.",
        "description_hi": "कब्ज में पेट साफ नहीं होता, मल सख्त हो जाता है जिससे पेट में भारीपन, गैस और पेट दर्द रहता है।",
        "severity": "mild",
        "severity_hi": "हल्का",
        "specialization": "General Medicine",
        "specialization_hi": "सामान्य चिकित्सक (General Physician)",
        "home_remedies_en": ["Drink warm water with lemon in the morning", "Eat high fiber foods (papaya, figs, oats, green vegetables)", "Drink 3 liters of water throughout the day", "Walk regularly after dinner"],
        "home_remedies_hi": ["सुबह उठकर गुनगुना पानी पिएं", "फाइबर युक्त चीजें (पपीता, अंजीर, हरी सब्जियां) खाएं", "दिन भर में 3 लीटर पानी पिएं", "रात के खाने के बाद टहलें"],
        "see_doctor_en": "Within a week if chronic",
        "see_doctor_hi": "यदि समस्या बनी रहे तो डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Piles": {
        "name_en": "Piles / Hemorrhoids",
        "name_hi": "बवासीर (पाइल्स)",
        "description_en": "Piles are swollen blood vessels in the lower rectum and anus, leading to painless bright red bleeding during bowel movements, itching, or pain.",
        "description_hi": "बवासीर में गुदा द्वार की नसें सूज जाती हैं, जिससे शौच के समय खून आना, दर्द, जलन और मस्सों में खुजली की तकलीफ होती है।",
        "severity": "moderate",
        "severity_hi": "मध्यम",
        "specialization": "General Surgery / Proctology",
        "specialization_hi": "शल्य चिकित्सक / गुदा रोग विशेषज्ञ",
        "home_remedies_en": ["Take warm water sitz bath for 15 minutes twice daily", "Prevent constipation by taking high fiber diet and isabgol", "Drink plenty of water", "Avoid sitting in toilet for prolonged time"],
        "home_remedies_hi": ["गुनगुने पानी के टब में 15 मिनट बैठें (सिट्ज़ बाथ)", "इसबगोल की भूसी और फाइबर खाएं ताकि कब्ज न हो", "खूब पानी पिएं", "शौचालय में ज्यादा देर जोर न लगाएं"],
        "see_doctor_en": "Within 2 to 3 days",
        "see_doctor_hi": "2-3 दिनों में डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Worm Infection": {
        "name_en": "Intestinal Worm Infection",
        "name_hi": "पेट के कीड़े (कृमि संक्रमण)",
        "description_en": "Worm infections occur when parasites inhabit the digestive tract, causing stomach ache, diarrhea, loss of appetite, itching around anus, and weight loss.",
        "description_hi": "पेट में परजीवी कीड़े होने से पेट में दर्द, भूख न लगना, गुदा के आसपास खुजली, दस्त और वजन कम होने लगता है।",
        "severity": "mild",
        "severity_hi": "हल्का",
        "specialization": "Pediatrics / General",
        "specialization_hi": "बाल रोग विशेषज्ञ / सामान्य चिकित्सक",
        "home_remedies_en": ["Take doctor-prescribed deworming tablet (albendazole)", "Wash hands thoroughly before meals and after toilet", "Eat thoroughly washed vegetables and clean cooked food", "Trim fingernails"],
        "home_remedies_hi": ["डॉक्टर की सलाह से पेट के कीड़े की दवा (एल्बेंडाजोल) लें", "खाना खाने से पहले और शौच के बाद हाथ साबुन से धोएं", "सब्जियों को अच्छी तरह धोकर पकाएं", "नाखून साफ व कटे रखें"],
        "see_doctor_en": "Within a week",
        "see_doctor_hi": "एक सप्ताह के भीतर डॉक्टर को दिखाएं",
        "emergency": False
    },
    "Heat Stroke": {
        "name_en": "Heat Stroke / Sunstroke",
        "name_hi": "लू लगना (हीट स्ट्रोक)",
        "description_en": "Heat stroke is a severe condition caused by body overheating in extreme summer heat, causing high body temperature, confusion, nausea, and fainting.",
        "description_hi": "तेज धूप और गर्मी में रहने से शरीर का तापमान बहुत अधिक बढ़ जाता है, जिससे तेज सिरदर्द, चक्कर, उल्टी, बेहोशी और लू लग जाती है।",
        "severity": "severe",
        "severity_hi": "अत्यंत गंभीर (आपातकालीन)",
        "specialization": "General Medicine / Emergency",
        "specialization_hi": "आपातकालीन चिकित्सा / सामान्य चिकित्सक",
        "home_remedies_en": ["Move person to a cool shady or air-conditioned room", "Sponge body with cool water or ice packs under armpits", "Give sips of cool water or ORS if conscious", "Rush to emergency if unconscious"],
        "home_remedies_hi": ["व्यक्ति को तुरंत ठंडी छांव वाले कमरे में ले जाएं", "पूरे शरीर पर ठंडे पानी की पट्टी रखें", "होश में होने पर ओआरएस या प्याज का रस व आम पना पिलाएं", "बेहोश होने पर तुरंत अस्पताल ले जाएं"],
        "see_doctor_en": "Today urgently",
        "see_doctor_hi": "तुरंत डॉक्टर / अस्पताल में दिखाएं",
        "emergency": True
    },
    "Dehydration": {
        "name_en": "Dehydration",
        "name_hi": "डिहाइड्रेशन (शरीर में पानी की कमी)",
        "description_en": "Dehydration occurs when the body loses more fluids and electrolytes than taken in, causing dry mouth, dark urine, extreme fatigue, and dizziness.",
        "description_hi": "शरीर से अधिक मात्रा में पसीना, उल्टी या दस्त से पानी निकल जाने पर मुंह सूखना, गहरा पेशाब, अत्यधिक कमजोरी और चक्कर आते हैं।",
        "severity": "moderate",
        "severity_hi": "मध्यम",
        "specialization": "General Medicine",
        "specialization_hi": "सामान्य चिकित्सक (General Physician)",
        "home_remedies_en": ["Drink ORS solution frequently in small sips", "Consume coconut water, lemon water, and buttermilk", "Rest in a cool place", "Avoid coffee, alcohol, and sugary sodas"],
        "home_remedies_hi": ["ओआरएस (ORS) का घोल घूंट-घूंट कर पिएं", "नारियल पानी, नींबू पानी और छाछ लें", "ठंडी जगह पर आराम करें", "चाय और ज्यादा मीठे पेय से बचें"],
        "see_doctor_en": "Within 1 to 2 days",
        "see_doctor_hi": "यदि पानी न टिके तो तुरंत डॉक्टर को दिखाएं",
        "emergency": False
    }
}
