keywords_map = {
    "bukhar": "high_fever",
    "high_fever": "high_fever",
    "garam": "high_fever",
    "tap": "high_fever",
    "jwar": "high_fever",
    "headache": "headache",
    "sir dard": "headache",
    "matha betha": "headache",
    "thandi": "chills",
    "chills": "chills",
    "pasina": "sweating",
    "sweating": "sweating",
    "ulti": "vomiting",
    "nausea": "nausea",
    "vomiting": "vomiting",
    "dast": "diarrhoea",
    "diarrhoea": "diarrhoea",
    "pet dard": "stomach pain",
    "stomach pain": "stomach pain",
    "badan dard": "body ache",
    "body ache": "body ache",
    "thakan": "fatigue",
    "fatigue": "fatigue",
    "khansi": "cough",
    "cough": "cough",
    "gala kharab": "sore throat",
    "sore throat": "sore throat",
    "naak behna": "running nose",
    "running nose": "running nose",
    "chhati me dard": "chest pain",
    "chest pain": "chest pain",
    "saans fulna": "shortness of breath",
    "difficulty breathing": "difficulty breathing",
    "wajan kam": "weight loss",
    "weight loss": "weight loss",
    "bhookh nahi": "loss of appetite",
    "loss of appetite": "loss of appetite",
    "pili chamdi": "yellow skin",
    "yellow skin": "yellow skin",
    "peshab me jalan": "burning sensation in urine",
    "kamjori": "weakness",
    "weakness": "weakness",
    "chakkar": "dizziness",
    "dizziness": "dizziness",
    "khujli": "itching",
    "itching": "itching",
    "lal ankh": "red eyes",
    "red eyes": "red eyes",
    "joint pain": "joint pain",
    "jodo me dard": "joint pain"
}